---

nginx:
  build: ./nginx/
  ports:
    - "80:80"
  volumes_from:
    - php
  volumes:
    - ./nginx/log:/var/log/nginx
  links:
    - php

php:
   build: ./php/
   volumes:
     - ./www:/www
   links:
     - mariadb

mariadb:
   image: mariadb
   restart: always
   volumes:
     - ./mariadb:/var/lib/mysql
   ports:
     - "3306:3306"
   environment:
       MYSQL_ROOT_PASSWORD: P2P121junm3
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: P2P121junm3
   expose:
     - "3306"

wordpress:
   image: wordpress
   volumes:
     - ./wordpress:/var/www/html
   ports:
     - "8080:80"
   links:
     - mariadb
   environment:
       WORDPRESS_DB_HOST: mariadb:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: P2P121junm3
       WORDPRESS_DB_NAME: wordpress
      
phpmyadmin:
   image: corbinu/docker-phpmyadmin
   restart: always
   links:
     - mariadb
   ports:
     - 8183:80
   environment:
       MYSQL_USERNAME: wordpress
       MYSQL_ROOT_PASSWORD: P2P121junm3
